In [1]:
#np.reshape(dimension1,dimension2,'C')(ROW WISE PRINT)
#np.reshape(dimension1,dimension2,'F')(COLUMN WISE PRINT)
#np.array()

In [4]:
import numpy as np
mydata=np.arange(0,20)
print(mydata)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [5]:
np.reshape(mydata,(5,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [7]:
MAT1=np.reshape(mydata,(5,4),order='C') #ROW WISE PRINT WHICH IS ALSO DEFAULT
MAT1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [9]:
#How to get elemnt of matrix
MAT1[2,2]

10

In [10]:
MAT2=np.reshape(mydata,(5,4),order='F') #COLUMN WISE PRINT
MAT2


array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [12]:
MAT2[0,2]

10

In [13]:
type(mydata)

numpy.ndarray

In [14]:
#so another mathod to do is not call the package numpy rather use object to call function.

In [17]:
mydata.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [18]:
mydata.reshape(5,4,order='f')

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

---

In [27]:
r1=['I','M','HAPPY']
r2=['What','a','DAY']
r3=[1,2,3]

In [28]:
[r1,r2,r3]

[['I', 'M', 'HAPPY'], ['What', 'a', 'DAY'], [1, 2, 3]]

In [29]:
np.array([r1,r2,r3])

array([['I', 'M', 'HAPPY'],
       ['What', 'a', 'DAY'],
       ['1', '2', '3']], dtype='<U5')

In [30]:
print(np.array([r1,r2,r3]))

[['I' 'M' 'HAPPY']
 ['What' 'a' 'DAY']
 ['1' '2' '3']]


In [1]:
#look at r3 list in array which is string with '' because each element of array needs to be of same data type.